#This file contains common configuration options for the two costmaps used in the navigation stack for more details on the parameters in this file, and a full list of the parameters used by the costmaps, please see http://www.ros.org/wiki/costmap_2d

#For this example we'll configure the costmap in voxel-grid mode
map_type: costmap


#Set the tolerance we're willing to have for tf transforms
transform_tolerance: 3.0
obstacle_range: 3.5
raytrace_range: 4.0

# footprint: [[-0.127, -0.127], [-0.18, 0.0], [-0.127, 0.127], [0.0, 0.18], [0.127, 0.127], [0.18, 0.0], [0.127, -0.127], [0.0, -0.18]]
# footprint: [[-0.25, -0.25], [-0.25, 0.0], [-0.25, 0.25], [0.0, 0.25], [0.25, 0.25], [0.25, 0.0], [0.25, -0.25], [0.0, -0.25]]

robot_radius: 0.17


footprint_padding: 0.03

update_frequency: 5.0

plugin:
  - {name: static_layer , type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer , type: "costmap_2d::VoxelLayer"}
  # - {name: inflation_layer , type: "costmap_2d::InflationLayer"}

static_layer:
  enabled: true
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.3
  update_frequency: 5.0
  rolling_window: false
  always_send_full_costmap: true
  lethal_cost_threshold: 65
  map_topic: map

obstacle_layer:
  enabled: true
  max_obstacle_height: 6.0
  obstacle_range: 2.5
  raytrace_range: 3.0
  track_unknown_space: false
  observation_sources: scan_laser
  
  scan_laser:
    topic: scan
    sensor_frame: base_scan
    data_type: LaserScan
    observation_persistence: 0.0
    # expected_update_rate: 0.3
    max_obstacle_height: 5.0
    min_obstacle_height: 0.0
    obstacle_range: 2.5
    raytrace_range: 3.0

  # global_inflation_layer:
  #   enabled: true
  #   inflation_radius: 5.0
  #   cost_scaling_factor: 5.0
# inflation_layer:
#   enable: true
#   inflation_radius: 1.0
#   cost_scaling_factor: 2.0
