# Move Base param
robot_radius: 0.2
footprint_padding: 0.05

controller_frequency: 20.0
controller_patience: 5.0

recovery_behavior_enabled: false

clearing_rotation_allowed: false

shutdown_costmaps: false

oscillation_distance: 0.5
oscillation_timeout: 10.0

planner_frequency: 0.0
planner_patience: 5.0

max_planning_retries: -1

base_global_planner: navfn/NavfnROS

# base_local_planner: teb_local_planner/TebLocalPlannerROS